I et forsøg på at løse to problemer på en gang - overholde formalia om implementering af algoritme i vores system, samtidig med at vi ønsker at skabe værdi for vores brugere - valgte vi at tilføje en algoritme, der skal udregne det ledige køretøj, som har den mindste tidsforskel (gap) mellem det valgte start- og sluttidspunkt. Ved at lade en bil med den mindste tidforskel være det optimale køretøj risikerer vi ikke en meget 'hullet' bookingkalender, hvor der spildes tid på små ledige intervaller mellem bookinger. Med et aftalt fokus på at skabe skelettet og bookingflowet som et udgangspunkt til refactoring, blev algoritmen i første omgang håndteret med moderne LINQ-sorteringsmetoder, OrderBy og OrderByDescending, der er relativt tunge sorteringer fremfor løkker med if-sætninger. På dette tidspunkt i processen var det en beslutning om at prioritere en kortere, mere læsbar kode, så vi hurtigst muligt kunne se effekten af vores arbejde. Da vores system heller ikke forventes at skulle håndtere så store datamængder, at LINQ-metoderne ville have en negativ påvirkning på bookingsystemets performance, blev det løsningen indtil videre.


Valg af asynkrone databasekald:
Med hensyn til vores databasekald har vi valgt at gøre dem asynkrone. Det er for det første god praksis, når man har med I/O at gøre og det sikrer, at UI-tråden ikke blokeres, mens databasekaldene udføres. Samtidig er det også for at forberede os på en fremtidig implementering, hvor systemet skal kunne håndtere samtidige brugerhandlinger mest effektivt. Som systemet er i øjeblikket er det ikke muligt for to tråde at have adgang til databasen på samme tid, da vi har taget en bevidst beslutning om kun at oprette en instans af vores Context-klasse, der skal køre i hele systemet. Da EF Core ikke er trådsikker, tillader det ikke at dele det nuværende systems eneste context-objekt. Her forhindrer vores async/await kald som sagt kun UI-tråden i at blive blokeret. Havde vi i stedet valgt at oprette flere midlertidige objekter af Context-klassen, som ville være nødvendigt, hvis vores bookingsystem skulle fungere i en distribueret kontekst, ville kombinationen af asynkron kode og flere instanser tillade vores EF Core at håndtere flere kald parallelt. Flere instanser ville gøre vores brug af EF Core trådsikker, fordi et context-objekt ikke længere ville blive delt mellem flere tråde. VI undgår, at EF Core crasher systemet, fordi to tråde forsøger at få adgang til samme context-objekt.

Valg af synkroniseringsmekanisme:
Da vores system deler en enkelt context-instans risikerer vi som sagt at få problemer, hvis to tråde vil have adgang til vores context på samme tid. Det kræver en form for trådhåndteringsmekanisme. Umiddelbart skulle vi implementere en sådan mekanisme alle de steder i vores system, hvor vi kalder databasen, men det ville skabe en rodet kode og være svær at vedligeholde. Alternativt skulle vi have implementeret en global lås, der helt ville udelukke risikoen for et crash. Dog ville sådan en global mekanisme også ødelægge alle fordelene ved vores asynkrone metoder. Med tanke på at vi arbejder hen imod en fremtidig skalering, hvor systemet skal kunne håndtere flere brugere og samtidige handlinger, virker sådan en implementering unødvendig i dette projekt. Skal bookingsystemet i fremtiden flyttes til en central server, ville hele synkroniseringensansvaret ligge hos databasens sikkerhedssystemer.De to ovennævnte muligheder løser altså ikke problemet, men symptombehandler et system, hvor årsagen i stedet skal findes i den fælles context-instans. Vi har i stedet valgt at implementere en SemaphoreSlim, der skal håndtere adgangen til vores mest kritiske del af koden, hvor en validering og en bookingoprettelse sker. Vores beslutning skal derfor ses mest som en demonstration af trådhåndtering inden for de rammer, projektet har og altså ikke en endelig løsning for en produktionsklar version.
Med henblik på vores forretningslogik, skal vi i vores lås sikre os, at kun en bruger kan booke et køretøj ad gangen, men samtidig skal bookingen ske hurtigt og effektivt. Vores valg af SemaphoreSlim er en effektiv løsning, da den er kompatibel med vores asynkrone metoder i modsætning til en synrkon semaphore eller fx en lock. En SemaphoreSlim opretter en asynkron kø. Når en tråd rammer en optaget lås, bliver kaldet sat i en form for dvale, der lader den underliggende tråd arbejde med noget andet imens der ventes - fuldstændig som vores asynkrone metoder gør. Det er en nødvendighed for en wpf-app, at UI-tråden ikke bliver blokeret. C\# vil ikke tillade en synkron lock at indeholde asynkron kode, og en synkron semaphore kunne man godt implementere rent teknisk, men den ville tvinge UI-tråden til at vente og skabe deadlock - blokeringen af UI-tråden vil fryse appen. Derfor er semaphoreslim det eneste logiske valg hvis man ønsker at demonstrere asynkron trådhåndtering på kodeniveau. Ved at give vores initialCount og derfor også vores maxCount en værdi på 1, (1, 1), sikrer vi, at kun en tråd får adgang ad gangen.
Det har fra planlægningsfasen været et bevidst valg at lave en struktur, der starter med at tjekke for det mest optimale køretøj i vores algoritme, og først derefter låser for at validere igen og oprette bookingen. Ideen var at holde vores semaphoreSlim så kort som muligt. Det var en bevidst optimistisk tilgang, da vi bygger til et fremtidigt system, hvor relativt få brugere skal booke køretøjer, hvorfor konflikter sker meget sjældent. Samtidig lægger vi os op ad princippet om at holde låse så korte som muligt. Mest af alt baserer denne beslutning sig på, at vi påtænker en form for retry-mekanisme, der skal tjekke for det næste optimale køretøj på listen, hvis valideringen i låsen afviser første forespørgsel. Havde vi placeret låsen før algoritmen, ville en sådan funktion ikke være mulig.
Desuden indeholder vores lås en finally-blok, der sikrer os mod en anden deadlock-situation, hvor en tråd blev låst fast. I den kalder vi Release(), så næste tråd får lov til at komme ind, uanset hvad der sker i try-blokken.









synkroniserings mekanisme: hvilken har vi valgt? Hvorfor har vi brugt en (domæne krav/værdiskabelse: kræver distribution af database)
asynkron kode: til IO
seperation of concerns i view/viewmodel -> medførte brugen af bindings
business rules: start-/endtime
ingen magiske tal
Design by contrant (invarianter i koden/statisk konstruktor til at garantere defaultDuration > minDuration)


