Vi manglede det store overblik over hele systemet. Det medførte, at vi kom igennem mange designcyklusser, hvor vi igen og igen ændrede på ting. Dette var især, fordi vi prioriterede at producere kode, frem for at lave mere "blødt" arbejde, da vi stadig ikke havde et basalt program, der kunne kompilere. Vi følte os bagude. Efter en procesvejledning blev det klart for os, at vi var nødt til at gå tilbage til tegnebrættet. Derfor arbejdede vi med et indledende sekvensdiagram over vores bookingflow, og et klassediagram, der skulle give os det store overblik og strømline vores mentale modeller.

#figure([#align(center)[#image("../assets/sekvensdiagram.svg", width: 100%)]], caption: [Sekvensdiagram])

Sekvensdiagrammet havde til formål at være et kommunikationsartefakt. Vi skulle blive enige om lagene og klassernes kontrakter (API'er), fordi vi havde svært ved at uddelegere programmeringsopgaver blandt os uden at vide, hvordan det vi lavede skulle snakke sammen. På trods af den gode intention fejlede diagrammet. Misforståelser opstod, og vi oplevede ikke vi lykkedes med at forventningsafstemme. Derfor forsøgte vi igen, men denne gang med et klassediagram.

#figure([#align(center)[#image("../assets/klassediagram-v2.svg", width: 100%)]], caption: [Klassediagram version 2])

Vi gik igennem to iterationer i dette modelleringsarbejde, fordi den første udgave (se @bilag:klassediagram-v1) stadig føltes unødvendig kompleks, da vi stadig oplevede for meget kognitiv friktion ved at implementere det. Oven i det følte vi os tidspressede, og derfor tog vi beslutningen om at reducere vores kvalitetskrav for at kunne skrive et _walking skeleton_, som bare kunne kompilere. Vi tænkte over at vi brød med vores forståelse af #cite(<larman2004>, form: "prose") beskrivelse af, hvilken kodekvalitet man skriver i et UP projekt. Ved at adoptere Proof of Concept fra en professionel kontekst til vores studiesituation (#link(<link:proof-of-ability>, [se Proof of Ability, afsnit 4.3])), retfærdiggjorde vi vores beslutning om at slippe perfektionismen og fokusere på at skrive "dårlig" kode, der virkede. Men med henblik på at iterere over det, alt efter hvad tiden tillod senere i projektet.
